import mongoose from "mongoose";
import dotenv from "dotenv";
import Book from "./models/Book.js";

dotenv.config();

const sampleBooks = [
  {
    bookId: "B001",
    title: "Database System Concepts",
    author: "Silberschatz, Korth, Sudarshan",
    isbn: "978-0078022159",
    category: "Database",
    publisher: "McGraw-Hill",
    year: 2019,
    totalCopies: 5,
    availableCopies: 3,
    description: "Fundamental concepts of database management, relational algebra, SQL, indexing, and transaction management.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B002",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    isbn: "978-0262035613",
    category: "Computer",
    publisher: "MIT Press",
    year: 2020,
    totalCopies: 6,
    availableCopies: 0, // Test 0 available copies
    description: "Comprehensive guide to modern algorithms, sorting, graph theory, and dynamic programming.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B003",
    title: "Operating System Concepts",
    author: "Abraham Silberschatz, Peter B. Galvin",
    isbn: "978-1118063330",
    category: "Computer",
    publisher: "Wiley",
    year: 2018,
    totalCopies: 4,
    availableCopies: 2,
    description: "Processes, threads, CPU scheduling, deadlocks, memory management, and virtual memory.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B004",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-0132350884",
    category: "Computer",
    publisher: "Prentice Hall",
    year: 2008,
    totalCopies: 5,
    availableCopies: 5,
    description: "A handbook of agile software craftsmanship, readable code design, unit testing, and refactoring.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B005",
    title: "Discrete Mathematics and Its Applications",
    author: "Kenneth H. Rosen",
    isbn: "978-1259676512",
    category: "Mathematics",
    publisher: "McGraw-Hill",
    year: 2019,
    totalCopies: 8,
    availableCopies: 4,
    description: "Sets, logic, proof techniques, graph theory, combinatorics, and algebraic structures.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B006",
    title: "Computer Networks: Top-Down Approach",
    author: "James Kurose, Keith Ross",
    isbn: "978-0133594140",
    category: "Computer",
    publisher: "Pearson",
    year: 2021,
    totalCopies: 4,
    availableCopies: 1,
    description: "Layered network architecture, HTTP, TCP/IP, routing algorithms, wireless, and network security.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B007",
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    isbn: "978-0134610993",
    category: "Computer",
    publisher: "Pearson",
    year: 2020,
    totalCopies: 3,
    availableCopies: 0,
    description: "Search algorithms, knowledge representation, probabilistic reasoning, machine learning, and robotics.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B008",
    title: "Higher Engineering Mathematics",
    author: "B.S. Grewal",
    isbn: "978-8174091955",
    category: "Mathematics",
    publisher: "Khanna Publishers",
    year: 2017,
    totalCopies: 10,
    availableCopies: 7,
    description: "Calculus, differential equations, linear algebra, vector calculus, and complex analysis.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B009",
    title: "High School English Grammar and Composition",
    author: "Wren & Martin",
    isbn: "978-9352530144",
    category: "English",
    publisher: "S. Chand",
    year: 2019,
    totalCopies: 6,
    availableCopies: 6,
    description: "Comprehensive English grammar, vocabulary building, essay writing, and sentence construction.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B010",
    title: "Fundamentals of Database Systems",
    author: "Ramez Elmasri, Shamkant B. Navathe",
    isbn: "978-0133970777",
    category: "Database",
    publisher: "Pearson",
    year: 2016,
    totalCopies: 5,
    availableCopies: 2,
    description: "ER modeling, normalization, transaction processing, concurrency control, and NoSQL databases.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B011",
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    isbn: "978-0201633610",
    category: "Computer",
    publisher: "Addison-Wesley",
    year: 1994,
    totalCopies: 4,
    availableCopies: 3,
    description: "Creational, structural, and behavioral design patterns for object-oriented design.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B012",
    title: "Linear Algebra and Its Applications",
    author: "David C. Lay, Steven R. Lay",
    isbn: "978-0321982384",
    category: "Mathematics",
    publisher: "Pearson",
    year: 2015,
    totalCopies: 7,
    availableCopies: 5,
    description: "Matrices, vector spaces, linear transformations, eigenvalues, and orthogonality.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B013",
    title: "Python Crash Course",
    author: "Eric Matthes",
    isbn: "978-1593279288",
    category: "Computer",
    publisher: "No Starch Press",
    year: 2019,
    totalCopies: 6,
    availableCopies: 4,
    description: "Hands-on, project-based introduction to programming in Python.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B014",
    title: "Word Power Made Easy",
    author: "Norman Lewis",
    isbn: "978-0143424680",
    category: "English",
    publisher: "Anchor",
    year: 2014,
    totalCopies: 8,
    availableCopies: 8,
    description: "Step-by-step vocabulary enrichment and vocabulary mastery guide.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B015",
    title: "NoSQL Distilled",
    author: "Pramod J. Sadalage, Martin Fowler",
    isbn: "978-0321826626",
    category: "Database",
    publisher: "Addison-Wesley",
    year: 2012,
    totalCopies: 4,
    availableCopies: 2,
    description: "A brief guide to the emerging world of polyglot persistence and non-relational databases.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B016",
    title: "Computer Organization and Architecture",
    author: "William Stallings",
    isbn: "978-0134997193",
    category: "Computer",
    publisher: "Pearson",
    year: 2018,
    totalCopies: 5,
    availableCopies: 1,
    description: "CPU design, instruction sets, memory hierarchy, bus organization, and parallel processing.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B017",
    title: "Calculus: Early Transcendentals",
    author: "James Stewart",
    isbn: "978-1285741550",
    category: "Mathematics",
    publisher: "Cengage Learning",
    year: 2015,
    totalCopies: 6,
    availableCopies: 3,
    description: "Limits, derivatives, integrals, infinite series, and multivariable calculus.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B018",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    isbn: "978-0135957059",
    category: "Computer",
    publisher: "Addison-Wesley",
    year: 2019,
    totalCopies: 5,
    availableCopies: 5,
    description: "Practical advice and philosophies for software developers to build career-long habits.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B019",
    title: "MongoDB: The Definitive Guide",
    author: "Shannon Bradshaw, Eoin Brazil",
    isbn: "978-1491954249",
    category: "Database",
    publisher: "O'Reilly Media",
    year: 2019,
    totalCopies: 4,
    availableCopies: 0,
    description: "Document storage, aggregation frameworks, indexing, sharding, and MongoDB administration.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B020",
    title: "Software Engineering: A Practitioner's Approach",
    author: "Roger S. Pressman",
    isbn: "978-0078022128",
    category: "Computer",
    publisher: "McGraw-Hill",
    year: 2014,
    totalCopies: 6,
    availableCopies: 4,
    description: "Software lifecycle models, requirements engineering, testing strategies, and project management.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B021",
    title: "Probability and Statistics for Engineers",
    author: "Ronald E. Walpole",
    isbn: "978-0321694010",
    category: "Mathematics",
    publisher: "Pearson",
    year: 2016,
    totalCopies: 7,
    availableCopies: 6,
    description: "Probability distributions, hypothesis testing, regression analysis, and ANOVA.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B022",
    title: "Effective Java",
    author: "Joshua Bloch",
    isbn: "978-0134685991",
    category: "Computer",
    publisher: "Addison-Wesley",
    year: 2017,
    totalCopies: 5,
    availableCopies: 2,
    description: "Best practices guide for the Java platform covering generics, concurrency, and serialization.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B023",
    title: "English Communication Skills for Engineers",
    author: "Meenakshi Raman, Sangeeta Sharma",
    isbn: "978-0199457068",
    category: "English",
    publisher: "Oxford University Press",
    year: 2015,
    totalCopies: 6,
    availableCopies: 4,
    description: "Professional speaking, technical report writing, presentation skills, and business correspondence.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B024",
    title: "SQL in 10 Minutes, Sams Teach Yourself",
    author: "Ben Forta",
    isbn: "978-0135182796",
    category: "Database",
    publisher: "Sams Publishing",
    year: 2019,
    totalCopies: 8,
    availableCopies: 7,
    description: "Quick, practical lesson format for learning standard SQL queries, joins, and subqueries.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B025",
    title: "Compilers: Principles, Techniques, and Tools",
    author: "Alfred V. Aho, Monica S. Lam",
    isbn: "978-0321486813",
    category: "Computer",
    publisher: "Pearson",
    year: 2006,
    totalCopies: 4,
    availableCopies: 1,
    description: "Lexical analysis, parsing, syntax-directed translation, code generation, and optimization.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B026",
    title: "Elementary Number Theory",
    author: "David M. Burton",
    isbn: "978-0073383118",
    category: "Mathematics",
    publisher: "McGraw-Hill",
    year: 2010,
    totalCopies: 5,
    availableCopies: 3,
    description: "Divisibility, primes, congruences, Fermat's theorem, and cryptographic applications.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B027",
    title: "Node.js Design Patterns",
    author: "Mario Casciaro, Luciano Mammino",
    isbn: "978-1839214110",
    category: "Computer",
    publisher: "Packt Publishing",
    year: 2020,
    totalCopies: 4,
    availableCopies: 2,
    description: "Asynchronous control flow, streams, microservices patterns, and scalable Node.js architecture.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B028",
    title: "Learning Web Design",
    author: "Jennifer Niederst Robbins",
    isbn: "978-1491960349",
    category: "Computer",
    publisher: "O'Reilly Media",
    year: 2018,
    totalCopies: 6,
    availableCopies: 5,
    description: "A beginner's guide to HTML, CSS, JavaScript, web graphics, and responsive design.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B029",
    title: "Database System Implementation",
    author: "Hector Garcia-Molina, Jeffrey D. Ullman",
    isbn: "978-0130402646",
    category: "Database",
    publisher: "Prentice Hall",
    year: 2008,
    totalCopies: 3,
    availableCopies: 0,
    description: "Storage structures, query execution, query optimization, failure recovery, and transaction processing.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B030",
    title: "Linear Algebra Done Right",
    author: "Sheldon Axler",
    isbn: "978-3319110790",
    category: "Mathematics",
    publisher: "Springer",
    year: 2015,
    totalCopies: 5,
    availableCopies: 4,
    description: "Proof-based approach to linear algebra focusing on vector spaces and linear maps.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B031",
    title: "You Don't Know JS Yet: Get Started",
    author: "Kyle Simpson",
    isbn: "978-1838848491",
    category: "Computer",
    publisher: "Independently published",
    year: 2020,
    totalCopies: 6,
    availableCopies: 6,
    description: "Deep dive into JavaScript core mechanics, scope, closures, objects, and prototype chains.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B032",
    title: "Technical Writing and Professional Communication",
    author: "Leslie O'Flahavan",
    isbn: "978-0070160248",
    category: "English",
    publisher: "McGraw-Hill",
    year: 2017,
    totalCopies: 4,
    availableCopies: 3,
    description: "Guidelines for writing clear technical proposals, manuals, and professional documentation.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B033",
    title: "Data Science from Scratch",
    author: "Joel Grus",
    isbn: "978-1492041139",
    category: "Computer",
    publisher: "O'Reilly Media",
    year: 2019,
    totalCopies: 5,
    availableCopies: 2,
    description: "First principles implementation of statistics, linear algebra, and machine learning models in Python.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B034",
    title: "Real-Time Systems",
    author: "Jane W. S. Liu",
    isbn: "978-0130568878",
    category: "Computer",
    publisher: "Pearson",
    year: 2000,
    totalCopies: 3,
    availableCopies: 1,
    description: "Scheduling algorithms, clock synchronization, real-time operating systems, and fault tolerance.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B035",
    title: "Differential Equations and Linear Algebra",
    author: "Stephen W. Goode, Scott A. Annin",
    isbn: "978-0321964670",
    category: "Mathematics",
    publisher: "Pearson",
    year: 2016,
    totalCopies: 6,
    availableCopies: 4,
    description: "Unified approach to first and second-order differential equations and linear algebra techniques.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B036",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    isbn: "978-1449373320",
    category: "Database",
    publisher: "O'Reilly Media",
    year: 2017,
    totalCopies: 8,
    availableCopies: 3,
    description: "The big ideas behind reliable, scalable, and maintainable distributed data storage systems.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B037",
    title: "Object-Oriented Analysis and Design with Applications",
    author: "Grady Booch",
    isbn: "978-0201895513",
    category: "Computer",
    publisher: "Addison-Wesley",
    year: 2007,
    totalCopies: 4,
    availableCopies: 2,
    description: "Object model principles, UML notation, system architecture, and case studies.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B038",
    title: "Complex Variables and Applications",
    author: "James Ward Brown, Ruel V. Churchill",
    isbn: "978-0073383170",
    category: "Mathematics",
    publisher: "McGraw-Hill",
    year: 2013,
    totalCopies: 5,
    availableCopies: 5,
    description: "Analytic functions, contour integration, Cauchy-Goursat theorem, and conformal mapping.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B039",
    title: "Head First Java",
    author: "Kathy Sierra, Bert Bates",
    isbn: "978-0596009205",
    category: "Computer",
    publisher: "O'Reilly Media",
    year: 2005,
    totalCopies: 7,
    availableCopies: 6,
    description: "Visually rich, beginner-friendly guide to object-oriented programming in Java.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B040",
    title: "Modern Database Management",
    author: "Jeffrey A. Hoffer, Ramesh Venkataraman",
    isbn: "978-0133544695",
    category: "Database",
    publisher: "Pearson",
    year: 2015,
    totalCopies: 5,
    availableCopies: 1,
    description: "Enterprise database development, SQL standards, data warehousing, and business intelligence.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B041",
    title: "Computer Graphics: Principles and Practice",
    author: "John F. Hughes, Andries van Dam",
    isbn: "978-0321399526",
    category: "Computer",
    publisher: "Addison-Wesley",
    year: 2013,
    totalCopies: 4,
    availableCopies: 0,
    description: "3D rendering pipeline, GPU programming, shading algorithms, and geometric modeling.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B042",
    title: "Graph Theory with Applications to Engineering",
    author: "Narsingh Deo",
    isbn: "978-8120301450",
    category: "Mathematics",
    publisher: "PHI Learning",
    year: 2004,
    totalCopies: 6,
    availableCopies: 3,
    description: "Trees, circuits, planarity, matrix representation of graphs, and network flow algorithms.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B043",
    title: "Professional English in Use",
    author: "Ian MacKenzie",
    isbn: "978-0521685436",
    category: "English",
    publisher: "Cambridge University Press",
    year: 2008,
    totalCopies: 5,
    availableCopies: 4,
    description: "Vocabulary development for finance, management, and technology professionals.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B044",
    title: "PostgreSQL: Up and Running",
    author: "Regina O. Obe, Leo S. Hsu",
    isbn: "978-1491963418",
    category: "Database",
    publisher: "O'Reilly Media",
    year: 2017,
    totalCopies: 4,
    availableCopies: 2,
    description: "Practical guide to PostgreSQL configuration, JSONB data types, indexing, and replication.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B045",
    title: "Cybersecurity Essentials",
    author: "Charles J. Brooks, Christopher Grow",
    isbn: "978-1119362395",
    category: "Computer",
    publisher: "Sybex",
    year: 2018,
    totalCopies: 6,
    availableCopies: 3,
    description: "Fundamental security concepts, threat analysis, cryptography, network security, and risk assessment.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B046",
    title: "Introduction to Mathematical Statistics",
    author: "Robert V. Hogg, Joseph McKean",
    isbn: "978-0134686998",
    category: "Mathematics",
    publisher: "Pearson",
    year: 2018,
    totalCopies: 5,
    availableCopies: 5,
    description: "Mathematical foundations of estimation theory, maximum likelihood, and statistical testing.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B047",
    title: "Learning React",
    author: "Alex Banks, Eve Porcello",
    isbn: "978-1492051725",
    category: "Computer",
    publisher: "O'Reilly Media",
    year: 2020,
    totalCopies: 7,
    availableCopies: 4,
    description: "Modern React development with Hooks, functional components, state management, and JSX syntax.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B048",
    title: "High-Performance MySQL",
    author: "Silvia Botros, Jeremy Tinley",
    isbn: "978-1492080510",
    category: "Database",
    publisher: "O'Reilly Media",
    year: 2021,
    totalCopies: 4,
    availableCopies: 2,
    description: "Optimization techniques, query tuning, indexing strategies, and high availability in MySQL.",
    syllabusRelated: true,
    img: "vector1.jpg"
  },
  {
    bookId: "B049",
    title: "Business Communication Today",
    author: "Courtland L. Bovee, John V. Thill",
    isbn: "978-0134562766",
    category: "English",
    publisher: "Pearson",
    year: 2017,
    totalCopies: 5,
    availableCopies: 5,
    description: "Corporate communication strategies, digital messages, employment communication, and public speaking.",
    syllabusRelated: false,
    img: "vector1.jpg"
  },
  {
    bookId: "B050",
    title: "Cloud Computing: Concepts, Technology & Architecture",
    author: "Thomas Erl, Zaigham Mahmood",
    isbn: "978-0133387520",
    category: "Computer",
    publisher: "Prentice Hall",
    year: 2013,
    totalCopies: 6,
    availableCopies: 3,
    description: "SaaS, PaaS, IaaS architecture, virtualization security, cloud delivery models, and cloud storage mechanics.",
    syllabusRelated: true,
    img: "vector1.jpg"
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB...");

    // Clear existing books collection
    await Book.deleteMany({});
    console.log("Cleared existing books collection.");

    // Map fields for backward compatibility
    const booksToInsert = sampleBooks.map(b => ({
      ...b,
      quantity: b.totalCopies,
      borrowed: b.totalCopies - b.availableCopies,
      createdAt: new Date(),
      updatedAt: new Date()
    }));

    await Book.insertMany(booksToInsert);
    console.log(`Successfully seeded ${booksToInsert.length} books into MongoDB database!`);

    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding books:", error);
    process.exit(1);
  }
}

seedDatabase();
